### PR TITLE
Full Backend Setup & Integration

### PR DESCRIPTION
**Pull request by Rishabhltfb**

### CODE REVIEW

**Comment by Rishabhltfb** [comment]
Build Check Failed Because Secrets aren't stored yet.
Please rerun the test after Storing Secrets.

**Comment by iamareebjamal** [comment]
Why so many commits in 1 PR? This defeats the purpose of Open Source development. Every change should have had a PR

**Comment by Rishabhltfb** [comment]
This mismanagement happens due to exams and busy schedules.Also, CI get broken due to a google-services issue and config files which gets resolved yesterday only.
From now on regular PRs will be made.

**Comment by Rishabhltfb** [comment]
I have tried creating a testing branch and merging pr in that branch. Build passes only after merge. Maybe first-time secrets aren't accessible to this pr.

**Pull request merged**
