### PR TITLE
feat: Event screen and Side Drawer

### PR DESCRIPTION
**Pull request by Rishabhltfb**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please add screenshots

**Comment by Rishabhltfb** [comment]
> Please add screenshots

design link: [](https://xd.adobe.com/view/bc6e0991-4af2-4433-bd1e-50a0784b1c96-e93d/grid)

**Comment by iamareebjamal** [comment]
That's design. Different from implementation. Add the actual screenshots

Like here https://github.com/fossasia/open-event-frontend/pull/5291

**Comment by Rishabhltfb** [comment]
<table>
  <tr>
    <td>AppBar</td>
     <td>SideDrawer</td>
  </tr>
  <tr>
    <td valign="top"> </td>
    <td valign="top"></td>
  </tr>
  <tr>
    <td>Light Theme</td>
     <td>Dark Theme</td>
  </tr>

<tr>
<td valign="top"></td>
<td valign="top"></td>
</tr>
    
 </table>

**Pull request merged**
