### PR TITLE
feat: normal user access restrictions

### PR DESCRIPTION
**Pull request by Rishabhltfb**
image

If the user email doesn't match the email in currTeam List then login access is denied.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Anyone should be allowed to login

**Comment by Rishabhltfb** [comment]
There is no use of login for normal users as we aren't providing anything that requires login.
As discussed with the team only core team members and faculty advisors are allowed to make profiles.

**Comment by iamareebjamal** [comment]
That is already not possible to do under firebase DB rules for users to create profiles

Secondly how do you know a person is core team member without logging that person is?

**Comment by Rishabhltfb** [comment]
we are working on a different database other than the website as the app and the website have nothing in common.
we are picking the user's email(from Gmail auth service) then checking it with the existing email list( stored on firestore) of the core team.

**Comment by iamareebjamal** [comment]
> we are working on a different database other than the website as the app and the website have nothing in common

Who said this? Where is this database hosted?

**Comment by Rishabhltfb** [comment]
App has a number of other features and demands another type of data modeling.
The current app has a profile, notifications, profiles, and much more with extra fields.
We do have a totally new way of showing events in this app, notifications are totally different than the previous one, project sections have much more data than only details, similarly, all the sections require new models. Therefore, we decide to go with firestore.
We are using firestore since it is better for querying and data caching and stores everything in form of documents.

**Comment by iamareebjamal** [comment]
> We are using firestore since it is better for querying and data caching and stores everything in form of documents.

Literally everything you said applies to Firebase DB as well. All the model changes you needed could have been added in firebase DB itself, as have been added over years. Software engineering isn't about throwing the old to add new when any change is needed. Tomorrow new team will come and need new models and extra fields, so to which technology will they switch after throwing away existing firestore DB? Mongo? Then next year postgres? Then Neo4J? Then something else. It seems we are choosing developer teams every year to just reimplement things which were created previously. 
When the idea was pitched about the Flutter app, I said yeah, Flutter would be easier to develop on, so go ahead but now it seems everything is being reimplemented from scratch

Now you have separated single source of truth with 2 sources, one for website, one for app.

Now you have to update the data in 2 places. Why are website features still being developed on Firebase DB? Feature to apply registration, delete projects? Why are we developing on 2 unrelated competing technologies. It doesn't make any sense.

In firebase DB repo, we had security rules to only allow controlled schemas and permissions which restricted non-admin users from accessing and writing data over existing data. Where are the firestore security rules? How are they being deployed? Why are they not open source? Are they even present? 

I can see there is no data in amu-roboclub firestore project, so it means the firebase project used is different one as well. I don't know why you guys want to unnecessarily complicate matters, but the open source project was created to ease the knowledge transfer over the years so everyone can see what's happening in the open using common project. If you want to switch back to non-transparent close source model where there is no idea who created what and why at the end of the year and separate website and app and go back to the way everything was, be my guest. You have the repo admin access, you can merge your PRs on your own

**Pull request merged**
